src/Entity/PayPalOrder.php
<?php

namespace App\Entity;

use App\Repository\PayPalOrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PayPalOrderRepository::class)]
class PayPalOrder
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private array $data = [];

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $paypal_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tracking_number = null;

    #[ORM\Column(nullable: true)]
    private ?bool $finalized = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getData(): array
    {
        return $this->data;
    }

    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPaypalId(): ?string
    {
        return $this->paypal_id;
    }

    public function setPaypalId(string $paypal_id): self
    {
        $this->paypal_id = $paypal_id;

        return $this;
    }

    public function getTrackingNumber(): ?string
    {
        return $this->tracking_number;
    }

    public function setTrackingNumber(?string $tracking_number): self
    {
        $this->tracking_number = $tracking_number;

        return $this;
    }

    public function isFinalized(): ?bool
    {
        return $this->finalized;
    }

    public function setFinalized(?bool $finalized): self
    {
        $this->finalized = $finalized;

        return $this;
    }

}

src/Controller/Dashboard/DashboardController.php
<?php

namespace App\Controller\Dashboard;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    #[Route('/admin', name: 'app_dashboard')]
    public function index(): Response
    {
        return $this->render('dashboard/index.html.twig');
    }
}

src/Controller/Dashboard/PayPalOrderController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\PayPalOrder;
use App\Service\PayPalOrderHelper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Routing\Annotation\Route;

class PayPalOrderController extends AbstractController
{
    #[Route('/admin/order', name: 'app_paypal_order_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $orders = $entityManager->getRepository(PayPalOrder::class)->findAll();

        return $this->render('dashboard/order/index.html.twig', [
            'orders' => $orders,
        ]);
    }

    #[Route('/admin/order/{paypal_id}', name: 'app_paypal_order_show', methods: ['GET'])]
    public function show(PayPalOrder $order, PayPalOrderHelper $helper): Response
    {
        $products = $helper->getProducts($order->getData());

        $countryName = Countries::getName($order->getData()['payer']['address']['country_code']);

        return $this->render('dashboard/order/show.html.twig', [
            'order' => $order,
            'orderData' => $order->getData(),
            'products' => $products,
            'country_name' => $countryName
        ]);
    }

    #[Route('/admin/order/{paypal_id}', name: 'app_paypal_order_update', methods: ['PUT'])]
    public function update(Request $request, PayPalOrder $order,  EntityManagerInterface $entityManager): Response
    {
        $order->setTrackingNumber($request->get('tracking_number'));
        $entityManager->persist($order);
        $entityManager->flush();

        $this->addFlash('success', 'Tracking number updated');

        return $this->redirectToRoute('app_paypal_order_show', ['paypal_id' => $order->getPaypalId()]);
    }

    #[Route('/admin/order/finalize', name: 'app_paypal_order_finalize', methods: ['POST'])]
    public function finalize(Request $request, EntityManagerInterface $entityManager, PayPalOrderHelper $helper): Response
    {
        $payPalId = $request->get('paypal_id');
        $order = $entityManager->getRepository(PayPalOrder::class)->findOneBy(['paypal_id' => $payPalId]);

        $redirectRoute = $this->redirectToRoute('app_paypal_order_show', ['paypal_id' => $order->getPaypalId()]);

        if (!$order->getTrackingNumber()) {
            $this->addFlash('error', 'Can not finalize order without tracking number');
            return $redirectRoute;
        }

        if ($order->isFinalized()) {
            $this->addFlash('error', 'Order already finalized');
            return $redirectRoute;
        }

        $order->setFinalized(true);
        $entityManager->persist($order);
        $entityManager->flush();

        $this->addFlash('success', 'Order finalized');

        $helper->sendShipmentConfirmationEmail($order);

        return $redirectRoute;
    }
}

src/Controller/Dashboard/ProductController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProductController extends AbstractController
{
    #[Route('/admin/product', name: 'app_product_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $products = $entityManager->getRepository(Product::class)->findAll();

        return $this->render('dashboard/product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/admin/product/create', name: 'app_product_create', methods: ['GET'])]
    public function create(): Response
    {
        return $this->render('dashboard/product/create.html.twig');
    }

    #[Route('/admin/product', name: 'app_product_store', methods: ['POST'])]
    public function store(Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response
    {
        // create instance
        $product = new Product();
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock((int)$request->get('stock') ?? null);
        $product->setImages($request->get('images'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }
            return $this->redirectToRoute('app_product_index');
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product saved');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}/edit', name: 'app_product_edit', methods: ['GET'])]
    public function edit(Product $product): Response
    {
        return $this->render('dashboard/product/edit.html.twig', [
            'product' => $product
        ]);
    }

    #[Route('/admin/product/{product}', name: 'app_product_update', methods: ['PUT'])]
    public function update(Request $request, Product $product, ValidatorInterface $validator, EntityManagerInterface $entityManager): Response
    {
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock($request->get('stock'));
        $product->setImages($request->get('images'));
        $product->setName($request->get('name'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }

            return $this->redirectToRoute('app_product_edit', ['product' => $product->getId()]);
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product updated');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}', name: 'app_product_delete', methods: ['DELETE'])]
    public function delete(Product $product, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product deleted');
        return $this->redirectToRoute('app_product_index');
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    #[Route('/admin', name: 'app_dashboard')]
    public function index(): Response
    {
        return $this->render('dashboard/index.html.twig');
    }
}

templates/dashboard/order/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}PayPal orders{% endblock %}

{% block body %}
    <div class="ui segment">
        <h2 class="ui left floated header">PayPal orders</h2>
        <div class="ui right floated header">
        </div>
        <div class="ui clearing divider">
        </div>

        <table class="ui celled table">
            <thead>
            <tr>
                <th>PayPal ID</th>
                <th>Finalized</th>
                <th>Created At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.paypalId }}</td>
                    <td class="collapsing">
                        {% if order.finalized == true %}
                            <i class="green check icon"></i>
                            <span>Yes</span>
                        {% else %}
                            <i class="red close icon"></i>
                            <span>No</span>
                        {% endif %}
                    </td>
                    <td class="collapsing">{{ order.createdAt | format_datetime('long') }}</td>
                    <td class="force-inline collapsing">
                        <a href="{{ path('app_paypal_order_show', {paypal_id: order.paypalId}) }}" class="ui button mini primary">View</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/dashboard/order/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Order #{{ orderData.id }}{% endblock %}

{% block body %}
    <div class="ui segment">
        <h2 class="ui left floated header">PayPal Order #{{ orderData.id }}</h2>
        <div class="ui right floated header">
            <form action="{{ path('app_paypal_order_finalize') }}" method="POST" class="ui form">
                <input type="hidden" name="paypal_id" value="{{ orderData['id'] }}">
                <button class="ui green button" id="finalize" {{ order.finalized ? 'disabled' : '' }}>Finalize order</button>
            </form>
        </div>
        <div class="ui clearing divider">
        </div>

        <h3>Order details</h3>
        <table class="ui table">
            <tr>
                <td>PayPal ID</td>
                <td class="collapsing">{{ orderData.id }}</td>
            </tr>
            <tr>
                <td>Finalized</td>
                <td class="collapsing">
                    {% if order.finalized %}
                        <i class="big check green icon"></i>
                        <span>Yes</span>
                    {% else %}
                        <i class="big red close icon"></i>
                        <span>No</span>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Created At</td>
                <td class="collapsing">{{ order.createdAt | format_datetime('long') }}</td>
            </tr>
        </table>

        <h3>Customer details</h3>
        <table class="ui table">
            <tr>
                <td>Given name</td>
                <td>{{ orderData['payer']['name']['given_name'] }}</td>
            </tr>
            <tr>
                <td>Surname</td>
                <td>{{ orderData['payer']['name']['surname'] }}</td>
            </tr>
            <tr>
                <td>E-mail address</td>
                <td class="collapsing">{{ orderData['payer']['email_address'] }}</td>
            </tr>
        </table>

        <h3>Shipping Label</h3>
        <div class="ui segment">
            <p>
                {{ orderData['purchase_units'][0]['shipping']['name']['full_name'] }}
                <br>
                {{ orderData['purchase_units'][0]['shipping']['address']['address_line_1'] }}
                <br>
                {{ orderData['purchase_units'][0]['shipping']['address']['postal_code'] }}&nbsp;&nbsp;{{ orderData['purchase_units'][0]['shipping']['address']['admin_area_2'] | upper }}
                <br>
                {{ country_name }}
            </p>
            <form action="{{ path('app_paypal_order_update', {paypal_id: orderData['id']}) }}" method="POST" class="ui form">
                <input type="hidden" name="_method" value="PUT">
                <div class="field" style="width: 600px">
                    <label for="">Tracking number</label>
                    <div class="ui action input">
                        <input type="text" name="tracking_number" value="{{ order.trackingNumber }}" required>
                        <button class="ui primary right labeled icon button">
                            <i class="dolly icon"></i>
                            Update tracking number
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <h3>Ordered products</h3>
        <table class="ui celled table">
            <thead>
            <tr>
                <th>Name</th>
                <th class="right aligned collapsing">Quantity</th>
                <th class="right aligned collapsing">Total</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        {{ product['name'] }}
                    </td>
                    <td>
                       {{ product['quantity'] }}
                    </td>
                    <td class="right aligned">
                        {{ (product['subtotal']) | format_currency('EUR') }}
                    </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
        <table class="ui table">
            <tr>
                <td>Subtotal</td>
                <td class="right aligned">
                        {{ (orderData['purchase_units'][0]['amount']['breakdown']['item_total']['value'])|format_currency('EUR') }}
                </td>
            </tr>
            <tr>
                <td>Shipping</td>
                <td class="right aligned">
                        {{ ( orderData['purchase_units'][0]['amount']['breakdown']['shipping']['value'])|format_currency('EUR') }}
                </td>
            </tr>
        </table>

        <div class="ui divider"></div>
        <table class="ui table">
            <tr>
                <td>
                    Total
                </td>
                <td class="right aligned">
                    {{ ( orderData['purchase_units'][0]['amount']['value'])|format_currency('EUR') }}
                </td>
            </tr>
        </table>
    </div>
{% endblock %}