src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $label = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotBlank]
    private ?string $price = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\Positive]
    private ?int $stock = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $images = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive]
    private ?int $max_allowed_per_order = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getImagesArray(): array
    {
        return \explode("\n", $this->images);
    }

    public function getMaxAllowedPerOrder(): ?int
    {
        return $this->max_allowed_per_order;
    }

    public function setMaxAllowedPerOrder(int $max_allowed_per_order): self
    {
        $this->max_allowed_per_order = $max_allowed_per_order;

        return $this;
    }
}

src/Controller/Shop/CartController.php
<?php

namespace App\Controller\Shop;

use App\Service\Cart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    public function __construct(private Cart $cart)
    {
    }

    #[Route('/cart/add', name: 'app_cart_add', methods: ['POST'])]
    public function add(Request $request): Response
    {
        $cart = $this->cart->getCart($request);
        $productId = (int)$request->get('product_id');
        $amount = (int)$request->get('amount');

        $amountAlreadyInCart = $cart[$productId] ?? 0;

        $newAmount = $amountAlreadyInCart + $amount;

        $cart[$productId] = $newAmount;

        $this->cart->setCart($request, $cart);

        return $this->redirect($request->headers->get('referer'));
    }

    #[Route('/cart/update', name: 'app_cart_update', methods: ['POST'])]
    public function update(Request $request): Response
    {
        $cart = $this->cart->getCart($request);
        $productId = (int)$request->get('product_id');
        $amount = (int)$request->get('amount');

        $newAmount = $amount;

        if ($newAmount < 0) {
            $newAmount = 0;
        }

        $cart[$productId] = $newAmount;

        $this->cart->setCart($request, $cart);

        return $this->redirect($request->headers->get('referer'));
    }


    #[Route('/cart/remove', name: 'app_cart_remove', methods: ['POST'])]
    public function remove(Request $request): Response
    {
        $cart = $this->cart->getCart($request);
        $productId = (int)$request->get('product_id');

        $newCart = array_filter($cart, function ($key) use ($productId) {
            return $key !== $productId;
        }, ARRAY_FILTER_USE_KEY);

        $this->cart->setCart($request, $newCart);

        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @deprecated
     * @param Request $request
     * @return Response
     */
    public function count(Request $request): Response
    {
        $cart = $this->cart->getCart($request);

        return new Response(count(array_keys($cart)), 200);
    }
}

src/Controller/Shop/ShopController.php
<?php

namespace App\Controller\Shop;

use App\Entity\Product;
use App\EntitySerializer;
use App\Service\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShopController extends AbstractController
{
    #[Route('/', name: 'app_shop')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        return $this->render('shop/index.html.twig');
    }

    #[Route('/products', name: 'app_shop_products')]
    public function products(EntityManagerInterface $entityManager): Response
    {
        $products = $entityManager->getRepository(Product::class)->findAll();

        return $this->render('shop/products.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/product/{label}', name: 'app_shop_product')]
    public function product(Product $product, Cart $cart, Request $request): Response
    {
        $amountInCart = $cart->getCart($request)[$product->getId()] ?? 0;

        if ($product->getMaxAllowedPerOrder() > $product->getStock()) {
            $maxAllowed = $product->getStock() - $amountInCart;
        } else {
            $maxAllowed = $product->getMaxAllowedPerOrder() - $amountInCart;
        }

        return $this->render('shop/product.html.twig', [
            'max_allowed' => $maxAllowed,
            'product' => $product
        ]);
    }

    #[Route('/cart', name: 'app_shop_cart')]
    public function cart(Request $request, Cart $cart, EntityManagerInterface $entityManager, EntitySerializer $serializer): Response
    {
        $cart = $cart->getCart($request);
        $serializedProducts = [];
        $subtotal = 0.0;

        foreach ($cart as $productId => $quantity) {
            $product = $entityManager->getRepository(Product::class)->find($productId);
            $serializedProduct = json_decode($serializer->serialize($product, 'json'), true);

            $serializedProduct['quantity'] = $quantity;

            if ($product->getMaxAllowedPerOrder() > $product->getStock()) {
                $maxAllowed = $product->getStock();
            } else {
                $maxAllowed = $product->getMaxAllowedPerOrder();
            }
            $serializedProduct['max_allowed'] = $maxAllowed;
            $serializedProduct['images'] = $product->getImagesArray();

            $serializedProducts[] = $serializedProduct;
            $subtotal += $product->getPrice() * $quantity;
        }

        return $this->render('shop/cart.html.twig', [
            'products' => array_filter($serializedProducts),
            'subtotal' => $subtotal
        ]);
    }

    #[Route('/success', name: 'order_success')]
    public function success(Request $request): Response
    {
        $request->getSession()->clear();
        return $this->render('shop/success.html.twig');
    }
}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Cart;
use App\Entity\Product;
use App\EntitySerializer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShopController extends AbstractController
{
    #[Route('/', name: 'app_shop')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        return $this->render('shop/index.html.twig');
    }

    #[Route('/products', name: 'app_shop_products')]
    public function products(EntityManagerInterface $entityManager): Response
    {
        $products = $entityManager->getRepository(Product::class)->findAll();

        return $this->render('shop/products.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/product/{label}', name: 'app_shop_product')]
    public function product(Product $product, Cart $cart, Request $request): Response
    {
        $amountInCart = $cart->getCart($request)[$product->getId()] ?? 0;

        if ($product->getMaxAllowedPerOrder() > $product->getStock()) {
            $maxAllowed = $product->getStock() - $amountInCart;
        } else {
            $maxAllowed = $product->getMaxAllowedPerOrder() - $amountInCart;
        }

        return $this->render('shop/product.html.twig', [
            'max_allowed' => $maxAllowed,
            'product' => $product
        ]);
    }

    #[Route('/cart', name: 'app_shop_cart')]
    public function cart(Request $request, Cart $cart, EntityManagerInterface $entityManager, EntitySerializer $serializer): Response
    {
        $cart = $cart->getCart($request);
        $serializedProducts = [];
        $subtotal = 0.0;

        foreach ($cart as $productId => $quantity) {
            $product = $entityManager->getRepository(Product::class)->find($productId);
            $serializedProduct = json_decode($serializer->serialize($product, 'json'), true);

            $serializedProduct['quantity'] = $quantity;

            if ($product->getMaxAllowedPerOrder() > $product->getStock()) {
                $maxAllowed = $product->getStock();
            } else {
                $maxAllowed = $product->getMaxAllowedPerOrder();
            }
            $serializedProduct['max_allowed'] = $maxAllowed;
            $serializedProduct['images'] = $product->getImagesArray();

            $serializedProducts[] = $serializedProduct;
            $subtotal += $product->getPrice() * $quantity;
        }

        return $this->render('shop/cart.html.twig', [
            'products' => array_filter($serializedProducts),
            'subtotal' => $subtotal
        ]);
    }

    #[Route('/success', name: 'order_success')]
    public function success(Request $request): Response
    {
        $request->getSession()->clear();
        return $this->render('shop/success.html.twig');
    }
}

templates/shop/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Shop - {% block title %}{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block extra_javascripts %}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
<h1>Shop</h1>
<p>
    {% set amountInCart %}
        {{ render(controller('App\\Controller\\Shop\\CartController::count')) }}
    {% endset %}
    Cart: {{ amountInCart }} |
    <a href="{{ path('app_shop_cart') }}">Checkout</a>
</p>
<div class="ui divider"></div>
<div class="force-inline">
    <a href="{{ path('app_shop') }}">Home</a> |
    <a href="{{ path('app_shop_products') }}">Products</a>
</div>
<div class="ui divider"></div>
{% block body %}{% endblock %}
</body>
</html>

templates/shop/cart.html.twig
{% extends 'shop/base.html.twig' %}

{% block extra_javascripts %}
    <script src="https://www.paypal.com/sdk/js?client-id=AaBR1U2Hox2ZIFvMit9nqRgvgQCxUjObxuDZcQ0WyIub99BK8dqQbPWPIujfRepYql5gxia4NEgSSUD1&components=buttons,messages&currency=EUR&debug=true&commit=false&disable-funding=card,paylater,bancontact,blik,eps,giropay,ideal,mercadopago,mybank,p24,sepa,sofort,venmo"></script>
{% endblock %}

{% block title %}Cart{% endblock %}

{% block body %}
    <h2>Your shopping cart</h2>

    {% if products %}
        <table class="table is-fullwidth cartpage">
            {% for product in products %}
                <tr>
                    <td style="width: 200px;">
                        <a class="cartlink" href="{{ path('app_shop_product', {label: product.label}) }}">
                            <img style="width: 150px;" src="{{ product.images | slice(0,1)[0]  }}" alt="{{ product.name }}">
                        </a>
                    </td>
                    <td>
                        <b>
                            <a class="cartlink" href="{{ path('app_shop_product', {label: product.label}) }}">
                                {{ product.name }}
                            </a>
                            <br>
                            <form action="{{ path('app_cart_remove') }}" method="POST">
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <button class="button is-inverted is-info" type="submit">Remove</button>
                            </form>
                        </b>
                        <br>
                    </td>
                    <td style="width: 80px;">
                        <b>
                            <form action="{{ path('app_cart_update') }}" method="POST">
                                <input type="hidden" name="product_id" value="{{ product['id'] }}">
                                <select
                                        {% if product['stock'] < 1 %}
                                            disabled="disabled"
                                        {% endif %}
                                        name="amount"
                                        class="input"
                                        onchange="this.form.submit()"
                                >
                                    {% for i in 1..product['max_allowed'] %}
                                        <option
                                                {% if product['quantity'] == i %}
                                                    selected="selected"
                                                {% endif %}
                                                value="{{ i }}"
                                        >
                                            {{ i }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </form>
                        </b>
                    </td>
                    <td style="width: 200px;" class="has-text-right">
                        {{ (product.price * product.quantity)|format_currency('EUR') }}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="ui divider"></div>
        <div class="subtotal is-pulled-right has-text-right">
            <h3>
              Subtotal:  {{ (subtotal)|format_currency('EUR') }}
            </h3>
            <p>
                Shipping calculated at checkout.
            </p>
            <br>
            <div class="is-pulled-right">
                <div id="paypal-button-container"></div>
            </div>
        </div>

    {% else %}
        <p>
            You have nothing in your shopping cart.
        </p>
        <p>
            <a href="/" class="button is-info">Continue shopping</a>
        </p>
    {% endif %}
{% endblock %}

{% block javascripts %}
<script>
    paypal.Buttons({
    // Sets up the transaction when a payment button is clicked
        createOrder: (data, actions) => {
            const createOrderUrl = '{{ path('paypal_create_order') }}';

            return fetch(createOrderUrl).then(function(response) {
                return response.json();
            }).then(function(order){
                return actions.order.create(order);
            });
        },

        // Finalize the transaction after payer approval
        onApprove: (data, actions) => {
            return actions.order.capture().then(function(orderData) {
                if (orderData.status === 'COMPLETED'){
                    fetch('{{ path('paypal_confirm_order') }}', {
                        method: "POST",
                        headers: {'Content-Type': 'application/json'},
                        body: JSON.stringify(orderData)
                    }).then(res => {
                        window.location.href = '{{ path('order_success') }}';
                    });
                }
            });
        }
    }).render('#paypal-button-container');
</script>
{% endblock %}

templates/shop/index.html.twig
{% extends 'shop/base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block body %}
    <h2>Homepage</h2>
    Homepage is empty for now :)
{% endblock %}

templates/shop/product.html.twig
{% extends 'shop/base.html.twig' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block body %}
    <h2>{{ product.name }}</h2>

    {% for image in product.imagesArray %}
        {% if image == null %}
            <img src="{{ asset('semantic-ui/examples/assets/images/wireframe/square-image.png') }}" width="256">
        {% endif %}
        <img src="{{ asset(image) }}" width="256">
    {% endfor %}

    <h3>{{ product.price | format_currency('EUR') }}</h3>

    <p>
        {{ product.description }}
    </p>

    <form action="{{ path('app_cart_add') }}" method="POST">
        <input type="hidden" name="product_id" value="{{ product.id }}">
        <label for="" class="label">Quantity</label>
        <select
                {% if product.stock < 1 or max_allowed < 1 %}
                    disabled="disabled"
                {% endif %}
                name="amount"
                class="ui input"
        >
            {% for i in 1..max_allowed %}
                <option value="{{ i }}">{{ i }}</option>
            {% endfor %}
        </select>

        <button
                class=" {{ product.stock < 1 ? 'red' : 'primary' }}"

                {% if product.stock < 1 or max_allowed < 1 %}
                    disabled="disabled"
                {% endif %}
        >
            {% if product.stock < 1 %}
                SOLD OUT
            {% else %}
                Add to cart
            {% endif %}
        </button>
    </form>
{% endblock %}

templates/shop/products.html.twig
{% extends 'shop/base.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <h2>Products</h2>
    {% for product in products %}
        {% for image in product.imagesArray | slice(0,1) %}
            {% if image == null %}
                <img src="{{ asset('semantic-ui/examples/assets/images/wireframe/square-image.png') }}" width="64">
            {% endif %}
            <img src="{{ asset(image) }}" width="64">
            <br>
        {% endfor %}
        <a href="{{ path('app_shop_product', {label: product.label}) }}">{{ product.name }}</a>
        <p>{{ product.price | format_currency('EUR') }}</p>
        <div class="ui divider"></div>
    {% endfor %}
{% endblock %}

templates/shop/success.html.twig
{% extends 'shop/base.html.twig' %}

{% block title %}Thank you for your order{% endblock %}

{% block body %}
    <h1></h1>
    <div class="ui success message">
        <div class="header">
            Thank you for your order
        </div>
        <p>
            You will receive an email confirmation shortly.
        </p>
    </div>
{% endblock %}