src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $label = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotBlank]
    private ?string $price = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\Positive]
    private ?int $stock = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $images = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive]
    private ?int $max_allowed_per_order = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getImagesArray(): array
    {
        return \explode("\n", $this->images);
    }

    public function getMaxAllowedPerOrder(): ?int
    {
        return $this->max_allowed_per_order;
    }

    public function setMaxAllowedPerOrder(int $max_allowed_per_order): self
    {
        $this->max_allowed_per_order = $max_allowed_per_order;

        return $this;
    }
}

src/Controller/Dashboard/DashboardController.php
<?php

namespace App\Controller\Dashboard;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    #[Route('/admin', name: 'app_dashboard')]
    public function index(): Response
    {
        return $this->render('dashboard/index.html.twig');
    }
}

src/Controller/Dashboard/PayPalOrderController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\PayPalOrder;
use App\Service\PayPalOrderHelper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Routing\Annotation\Route;

class PayPalOrderController extends AbstractController
{
    #[Route('/admin/order', name: 'app_paypal_order_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $orders = $entityManager->getRepository(PayPalOrder::class)->findAll();

        return $this->render('dashboard/order/index.html.twig', [
            'orders' => $orders,
        ]);
    }

    #[Route('/admin/order/{paypal_id}', name: 'app_paypal_order_show', methods: ['GET'])]
    public function show(PayPalOrder $order, PayPalOrderHelper $helper): Response
    {
        $products = $helper->getProducts($order->getData());

        $countryName = Countries::getName($order->getData()['payer']['address']['country_code']);

        return $this->render('dashboard/order/show.html.twig', [
            'order' => $order,
            'orderData' => $order->getData(),
            'products' => $products,
            'country_name' => $countryName
        ]);
    }

    #[Route('/admin/order/{paypal_id}', name: 'app_paypal_order_update', methods: ['PUT'])]
    public function update(Request $request, PayPalOrder $order,  EntityManagerInterface $entityManager): Response
    {
        $order->setTrackingNumber($request->get('tracking_number'));
        $entityManager->persist($order);
        $entityManager->flush();

        $this->addFlash('success', 'Tracking number updated');

        return $this->redirectToRoute('app_paypal_order_show', ['paypal_id' => $order->getPaypalId()]);
    }

    #[Route('/admin/order/finalize', name: 'app_paypal_order_finalize', methods: ['POST'])]
    public function finalize(Request $request, EntityManagerInterface $entityManager, PayPalOrderHelper $helper): Response
    {
        $payPalId = $request->get('paypal_id');
        $order = $entityManager->getRepository(PayPalOrder::class)->findOneBy(['paypal_id' => $payPalId]);

        $redirectRoute = $this->redirectToRoute('app_paypal_order_show', ['paypal_id' => $order->getPaypalId()]);

        if (!$order->getTrackingNumber()) {
            $this->addFlash('error', 'Can not finalize order without tracking number');
            return $redirectRoute;
        }

        if ($order->isFinalized()) {
            $this->addFlash('error', 'Order already finalized');
            return $redirectRoute;
        }

        $order->setFinalized(true);
        $entityManager->persist($order);
        $entityManager->flush();

        $this->addFlash('success', 'Order finalized');

        $helper->sendShipmentConfirmationEmail($order);

        return $redirectRoute;
    }
}

src/Controller/Dashboard/ProductController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProductController extends AbstractController
{
    #[Route('/admin/product', name: 'app_product_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $products = $entityManager->getRepository(Product::class)->findAll();

        return $this->render('dashboard/product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/admin/product/create', name: 'app_product_create', methods: ['GET'])]
    public function create(): Response
    {
        return $this->render('dashboard/product/create.html.twig');
    }

    #[Route('/admin/product', name: 'app_product_store', methods: ['POST'])]
    public function store(Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response
    {
        // create instance
        $product = new Product();
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock((int)$request->get('stock') ?? null);
        $product->setImages($request->get('images'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }
            return $this->redirectToRoute('app_product_index');
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product saved');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}/edit', name: 'app_product_edit', methods: ['GET'])]
    public function edit(Product $product): Response
    {
        return $this->render('dashboard/product/edit.html.twig', [
            'product' => $product
        ]);
    }

    #[Route('/admin/product/{product}', name: 'app_product_update', methods: ['PUT'])]
    public function update(Request $request, Product $product, ValidatorInterface $validator, EntityManagerInterface $entityManager): Response
    {
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock($request->get('stock'));
        $product->setImages($request->get('images'));
        $product->setName($request->get('name'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }

            return $this->redirectToRoute('app_product_edit', ['product' => $product->getId()]);
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product updated');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}', name: 'app_product_delete', methods: ['DELETE'])]
    public function delete(Product $product, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product deleted');
        return $this->redirectToRoute('app_product_index');
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    #[Route('/admin', name: 'app_dashboard')]
    public function index(): Response
    {
        return $this->render('dashboard/index.html.twig');
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProductController extends AbstractController
{
    #[Route('/admin/product', name: 'app_product_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $products = $entityManager->getRepository(Product::class)->findAll();

        return $this->render('dashboard/product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/admin/product/create', name: 'app_product_create', methods: ['GET'])]
    public function create(): Response
    {
        return $this->render('dashboard/product/create.html.twig');
    }

    #[Route('/admin/product', name: 'app_product_store', methods: ['POST'])]
    public function store(Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response
    {
        // create instance
        $product = new Product();
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock((int)$request->get('stock') ?? null);
        $product->setImages($request->get('images'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }
            return $this->redirectToRoute('app_product_index');
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product saved');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}/edit', name: 'app_product_edit', methods: ['GET'])]
    public function edit(Product $product): Response
    {
        return $this->render('dashboard/product/edit.html.twig', [
            'product' => $product
        ]);
    }

    #[Route('/admin/product/{product}', name: 'app_product_update', methods: ['PUT'])]
    public function update(Request $request, Product $product, ValidatorInterface $validator, EntityManagerInterface $entityManager): Response
    {
        $product->setName($request->get('name'));
        $product->setLabel($request->get('label'));
        $product->setPrice($request->get('price'));
        $product->setDescription($request->get('description'));
        $product->setStock($request->get('stock'));
        $product->setImages($request->get('images'));
        $product->setName($request->get('name'));
        $product->setMaxAllowedPerOrder($request->get('max_allowed_per_order'));

        // check errors
        $errors = $validator->validate($product);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $this->addFlash('error', $error->getpropertyPath() . ': ' . $error->getMessage());
            }

            return $this->redirectToRoute('app_product_edit', ['product' => $product->getId()]);
        }

        // persist
        $entityManager->persist($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product updated');
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/admin/product/{product}', name: 'app_product_delete', methods: ['DELETE'])]
    public function delete(Product $product, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($product);
        $entityManager->flush();

        $this->addFlash('success', 'Product deleted');
        return $this->redirectToRoute('app_product_index');
    }
}

templates/dashboard/product/create.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Create Product{% endblock %}

{% block body %}
    <div class="ui segment">
        <h2 class="ui left floated header">Create Product</h2>
        <div class="ui clearing divider">
        </div>
        <form action="{{ path('app_product_store') }}" method="POST" class="ui form">
            <div class="field">
                <label>Name</label>
                <input type="text" name="name" placeholder="Name">
            </div>
            <div class="field">
                <label>Label</label>
                <input type="text" name="label" placeholder="Label">
            </div>
            <div class="field">
                <label>Price</label>
                <input type="text" name="price" placeholder="Price">
            </div>
            <div class="field">
                <label>Stock</label>
                <input type="number" name="stock" placeholder="Stock">
            </div>
            <div class="field">
                <label>Max allowed per order</label>
                <input type="number" name="max_allowed_per_order" placeholder="Max allowed per order" value="{{ product.maxAllowedPerOrder }}">
            </div>
            <div class="field">
                <label>Description</label>
                <textarea name="description" cols="30" rows="10"></textarea>
            </div>
            <div class="field">
                <label>Images</label>
                <textarea name="images" cols="30" rows="4"></textarea>
            </div>
            <button class="ui green button" type="submit">Save Product</button>
        </form>
    </div>

{% endblock %}

templates/dashboard/product/edit.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <div class="ui segment">
        <h2 class="ui left floated header">Edit Product</h2>
        <div class="ui clearing divider">
        </div>
        <form action="{{ path('app_product_update', {product: product.id}) }}" method="POST" class="ui form">
            <input type="hidden" name="_method" value="PUT">
            <div class="field">
                <label>Name</label>
                <input type="text" name="name" placeholder="Name" value="{{ product.name }}">
            </div>
            <div class="field">
                <label>Label</label>
                <input type="text" name="label" placeholder="Label" value="{{ product.label }}">
            </div>
            <div class="field">
                <label>Price</label>
                <input type="text" name="price" placeholder="Price" value="{{ product.price }}">
            </div>
            <div class="field">
                <label>Stock</label>
                <input type="number" name="stock" placeholder="Stock" value="{{ product.stock }}">
            </div>
            <div class="field">
                <label>Max allowed per order</label>
                <input type="number" name="max_allowed_per_order" placeholder="Max allowed per order" value="{{ product.maxAllowedPerOrder }}">
            </div>
            <div class="field">
                <label>Description</label>
                <textarea name="description" cols="30" rows="10">{{ product.description  }}</textarea>
            </div>
            <div class="field">
                <label>Images</label>
                <textarea name="images" cols="30" rows="4">{{ product.images }}</textarea>
            </div>
            <button class="ui green button" type="submit">Save Product</button>
        </form>
    </div>
{% endblock %}

templates/dashboard/product/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <div class="ui segment">
        <h2 class="ui left floated header">Products</h2>
        <div class="ui right floated header">
            <a href="{{ path('app_product_create') }}" class="button ui primary button">
                Create Product
            </a>
        </div>
        <div class="ui clearing divider">
        </div>

        <table class="ui celled table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Label</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Stock</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td class="collapsing">{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.label }}</td>
                    <td class="collapsing">{{ product.price | format_currency('EUR') }}</td>
                    <td>{{ product.description }}</td>
                    <td class="collapsing">{{ product.stock }}</td>
                    <td class="collapsing force-inline">
                        <a href="{{ path('app_product_edit', {product: product.id}) }}" class="mini ui button">
                            Edit
                        </a>
                        <form action="{{ path('app_product_delete', {product: product.id}) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="mini ui red button">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}